### ISSUE TITLE
Not able to use SSH from Hetzner

### ISSUE THREAD

**Issue by larsstrandos** [deyaeddin/terraform-hcloud-k3s-ext#1]
Hi,
I am not able to import the SSH key from hetzner as I am with their own hcloud module, any soultion to this

Example:
resource "hcloud_server" "kubes" {
    count       = 3
    name        = "kube-${count.index + 1}"
    image       = "debian-10"
    server_type = "cx11"
    ssh_keys = [ "sshkey name" ]
}

**Comment by larsstrandos** [comment]
![image](https://user-images.githubusercontent.com/60901214/126016639-05416451-1030-4273-9457-96beda78c4a7.png)

**Comment by deyaeddin** [comment]
hi @larsstrandos 
In order to use this model, you need to generate the SSH key or use an existing one, and then use its path as a parameter.
if you have one on Hetzner already, just download it and use the path. let me know if that's helped.

**Comment by larsstrandos** [comment]
I doesn't get that error when I have a id_rsa key generated and running it on my local machine. But I am normally running Terraform trough Gitlab CI, so then I would rather use a variable with the public key. And here was something else that came up.
![image](https://user-images.githubusercontent.com/60901214/126048017-92d4a3b4-1179-4f29-99ef-0db3501af228.png)

**Comment by deyaeddin** [comment]
When you run on any CI platform, you need to create a folder to contain SSH keys and config files, then pass the paths as variables.

for example:
`in your .gitlab-ci.yml  mkdir /temp/NEW-DIRECTORY ` then generate the keys or copy them inside NEW-DIRECTORY

After that pass:
```
k3s_config_file   = "/temp/NEW-DIRECTORY/hetzner.config"
public_key_path =  "/temp/NEW-DIRECTORY/id_rsa.pub"
```
